sudo: required
language: c
env:
  - TESTS_MODE=build-in-tests TEST_RUNS=10000
  - TESTS_MODE=deep-expressions-tests
cache:
  directories:
  - "$HOME/.stack"
  - "$HOME/build/compiler/.stack-work"
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
- sudo apt-get install gcc-multilib
install:
- stack --no-terminal --install-ghc build --only-dependencies --jobs=4
- cd runtime && make && cd ..
script:
- make $TESTS_MODE TEST_RUNS=$TEST_RUNS
- make clean
