sudo: required
language: c
cache:
  directories:
  - "$HOME/.stack"
  - "$HOME/build/compiler/.stack-work"
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
- sudo apt-get install gcc-multilib
install:
- stack --no-terminal --install-ghc build --only-dependencies --jobs=4
- cd runtime && make && cd ..
script:
- stack --no-terminal build --test --jobs=4 --test-arguments --qc-max-success=1000
- travis_wait 60 ./check.sh expressions
- ./check.sh deep-expressions
